export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ITEM_REMOVE = 'ITEM_REMOVE';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const ADD_TRANSPORT = 'ADD_TRANSPORT';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';