export const SORT_ITEMS_AZ = 'SORT_ITEMS_AZ';
export const SORT_ITEMS_ZA = 'SORT_ITEMS_ZA';
export const SORT_ITEMS_PRICEI = 'SORT_ITEMS_PRICEI';
export const SORT_ITEMS_PRICED = 'SORT_ITEMS_PRICED';
export const GET_ITEM = 'GET_ITEM';